# Generated by Django 4.2.6 on 2023-12-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_vendeur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendeur',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
