# Generated by Django 4.2.6 on 2023-12-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_vendeur_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Vendeur',
        ),
        migrations.AlterField(
            model_name='patient',
            name='medecin_attitré',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.medecins'),
        ),
        migrations.DeleteModel(
            name='Medecin',
        ),
    ]
