# Generated by Django 4.2.6 on 2023-12-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_specialite_medecin_specialite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexe', models.CharField(max_length=15)),
                ('age', models.IntegerField(null=True)),
                ('poids', models.IntegerField(null=True)),
                ('antecedent', models.TextField(null=True)),
                ('prescription', models.TextField(null=True)),
            ],
        ),
    ]
