# Generated by Django 4.2.6 on 2023-12-26 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_consultation_prescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
