# Generated by Django 4.2.6 on 2023-12-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='prescription',
            new_name='prescription1',
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription3',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
