# Generated by Django 4.2.6 on 2023-12-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_rename_prescription_prescription_prescription1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
