# Generated by Django 4.2.6 on 2023-12-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_consultation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
