# Generated by Django 4.2.6 on 2023-12-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_prescription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
