# Generated by Django 4.2.6 on 2023-12-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_prescription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='Date',
        ),
    ]
