# Generated by Django 4.2.6 on 2023-12-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_remove_prescription_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
    ]
