# Generated by Django 4.2.6 on 2023-12-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_donne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donne',
        ),
    ]
