# Generated by Django 4.2.6 on 2023-12-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_delete_donne'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='Token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
