# Generated by Django 4.2.6 on 2023-12-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_prescription_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='service',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='sexe',
            field=models.CharField(max_length=50),
        ),
    ]
